dist: trusty
sudo: required
before_script: test_helpers/install_nodejs4.sh
matrix:
  include:
    - before_script:
        - export DISPLAY=:99.0
        - sh -e /etc/init.d/xvfb start
        - test_helpers/install_nodejs4.sh
        - sudo test_helpers/install_regtest.sh
        - mv karma.conf.js-discovery karma.conf.js
        - cp lib/trezor-crypto/emscripten/trezor-crypto.js test/trezor-crypto.js
        - cp lib/trezor-crypto/emscripten/trezor-crypto.wasm test/trezor-crypto.wasm
      env: TEST_SUITE=karma-firefox TEST=discovery
      addons:
        firefox: latest

env:
  - TEST_SUITE=eslint
script: npm run-script $TEST_SUITE
